# Generated by Django 6.0 on 2025-12-16 13:09

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_freesample_alter_downloadhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(default=shop.models.get_current_year, help_text='Year the paper was administered'),
        ),
    ]
