# Generated by Django 6.0 on 2025-12-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_questionpaper_slug_alter_questionpaper_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='downloadhistory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='questionpaper',
            name='shop_questi_slug_fd2524_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionpaper',
            name='shop_questi_class_l_bf4478_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionpaper',
            name='shop_questi_is_avai_ff0744_idx',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Mid-Term Exam'), ('endterm', 'End-Term Exam'), ('cat', 'CAT'), ('assignment', 'Assignment'), ('final', 'Final Exam'), ('mock', 'Mock Exam'), ('others', 'Others')], default='endterm', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to='question_papers/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='shop.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.questionpaper'),
        ),
    ]
